name = "DFExt"
uuid = "2ebabd8a-cedd-4813-a5cc-cb56fda28c08"
authors = ["Paco Ho"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
