name = "DFExt"
uuid = "2ebabd8a-cedd-4813-a5cc-cb56fda28c08"
authors = ["Paco Ho"]
version = "0.1.0"

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"
XLSX = "fdbf4ff8-1666-58a4-91e7-1b58723a45e0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]

[sources]
WebTools = {url="https://github.com/pacotimekeeper/WebTools.jl.git"}
